default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: norbapp_api_development

test:
  <<: *default
  database: norbapp_api_test

production:
  <<: *default
  database: norbapp_api_production
  username: deploy
  password: <%= ENV['NORBAPP_API_DATABASE_PASSWORD'] %>
  password: Rails.application.credentials.dig(:production, :db_password)
